name: Release project
on:
  workflow_dispatch:

jobs:
  build_and_test:
    uses: cscoding21/cscoding/.github/workflows/go-build.yaml@main

  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    needs: build_and_test
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0

      - name: Create temporary branch
        run: git switch -c "release/${{ github.sha }}"

      # switch to the temporary branch
      - name: Switch to new branch
        run: git push -u origin release/${{ github.sha }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create bump and changelog
        id: changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          debug: true
          branch: release/${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

       # create PR using GitHub CLI
      - name: Create PR with release info
        if: steps.changelog.outputs.skipped == 'false'
        id: create-pr
        run: gh pr create --base main --head release-from-${{ github.sha }} --title 'Merge new release into main' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # merge PR using GitHub CLI
      - name: merge PR with release info
        if: steps.changelog.outputs.skipped == 'false'
        id: merge-pr
        run: gh pr merge --admin --merge --subject 'Merge release info' --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

  notification:
    # Discord notification
    # https://github.com/marketplace/actions/actions-for-discord
    runs-on: ubuntu-latest
    needs: bump_version
    name: "Create Discord notification"
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
    